version: "3.8"
services:
  db:
      image: postgres:latest
      restart: always
      env_file:
        - ./.envs/.postgresql
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: ./Docker/django/Dockerfile
    image: library_api
    container_name: library_api
    ports:
      - 8000:8000
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - ./.envs/.django
      - ./.envs/.env

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data

  ui:
    build:
      context: .
      dockerfile: ./Docker/nodejs/Dockerfile
    image: library_ui
    container_name: library_ui
    ports:
      - 5173:5173

volumes:
  data:
  postgres_data:
    driver: local
  cache:
    driver: local
